name: build--checkout

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: '分支名称'
        required: true
        default: 'master'
      token:
        description: 'token'
        required: true
        default: 'bc53e10960aa138d07e15d7eb95e6acf'
      owner:
        description: 'owner'
        required: true
        default: 'openwz'
      project-name:
        description: '项目名称'
        required: true
        default: 'react-web'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 使用自定义 [代码检出] Checkout 插件
        id: meact
        uses: wzjerrywz/github-actions/build-checkout@v1.6.1007
        with:
          branch-name: ${{ inputs.branch-name }}
          token: ${{ inputs.token }}
          owner: ${{ inputs.owner }}
          project-name: ${{ inputs.project-name }}

      - name: out [输出结果] 
        run: |
          ls -l ./${{ inputs.project-name }}

