# .github/workflows/use-my-action.yml
name: Use My TypeScript Action
inputs:
  source-directory:
    description: 'Directory containing files to process'
    required: true

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: 使用自定义 Action
        id: meact
        uses: wzjerrywz/meact@v0.0.1
        with:
          hello-world: '这是企业苏州'
      
