# .github/workflows/use-my-action.yml
name: Use My TypeScript Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: 安装依赖
        run: npm install @actions/core -g
      - name: 使用自定义 Action
        id: my-action
        uses: wzjerrywz/myts-action@v0.0.2
        with:
          name: 'GitHub Actions'
          message: 'This is a test'
      
      - name: 打印输出
        run: |
          echo "Greeting: ${{ steps.my-action.outputs.greeting }}"
