name: mixed--gradle--build

on:
  workflow_dispatch:
    inputs:
      ##################  checkout ##########################  
      repo-name:
        description: '1@checkout. 仓库名称'
        required: true
        type: choice
        default: 'gitee/demo-gradle-groovy-build'
        options:
          - gitee/demo-vue3-npm
          - gitee/demo-vue3-yarn
          - gitee/demo-python312-pip
          - gitee/demo-dotnet-nuget
          - gitee/demo-gradle-groovy-build
      branch-name:
        description: '1@checkout. 分支名称'
        required: true
        type: choice
        default: 'master'
        options:
          - master
          - dev
          - test    
      ##################  openjdk ##########################  
      jdk-version:
        description: '2@jdk. jdk 版本'
        required: true
        type: string
        default: '17.0.2'
      jdk-install-path:
        description: '2@jdk. jdk 安装路径'
        required: true
        type: string
        default: './soft/jdk'
      ##################  gradle ##########################  
      gradle-version:
        description: '3@gradle. gradle 版本'
        required: true
        type: string
        default: '9.1.0'
      gradle-install-path:
        description: '3@gradle. gradle 安装路径'
        required: true
        type: string
        default: './soft/gradle'
      ##################  build - gradle ##########################  
      work-dir:
        description: '4@build. 工作目录'
        required: true
        type: string
        default: './demo-gradle-groovy-build'
      build-cmd:
        description: '4@build. 构建命令'
        required: true
        type: string
        default: 'build'        
                  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1.自定义 [ repo-checkout ] 插件
        id: checkout
        uses: wzjerrywz/github-actions/repo-checkout@main
        with:
          repo-name: ${{ inputs.repo-name }}
          branch-name: ${{ inputs.branch-name }}
          gitee-username: work_666_9527
          gitee-token: bc53e10960aa138d07e15d7eb95e6acf

      - name: step2.自定义 [ setup-openjdk ] 插件
        id: openjdk
        uses: wzjerrywz/github-actions/setup-openjdk@main
        with:
          jdk-version: ${{ inputs.jdk-version }}
          install-path: ${{ inputs.jdk-install-path }}

      - name: step3.自定义 [ setup-gradle] 插件
        id: gradle
        uses: wzjerrywz/github-actions/setup-gradle@main
        with:
          gradle-version: ${{ inputs.gradle-version }}
          install-path: ${{ inputs.gradle-install-path }}

      - name: step4.自定义 [ build-gradle] 插件
        id: build
        uses: wzjerrywz/github-actions/build-gradle@main
        with:
          work-dir: ${{ inputs.work-dir }}
          build-cmd: ${{ inputs.build-cmd }}