name: mixed--npm

on:
  workflow_dispatch:
    inputs:
      ##################  checkout ##########################  
      actions-version:
        description: '1@checkout. actions 版本'
        required: true
        default: 'v1.16.1007'
      branch-name:
        description: '1@checkout. 分支名称'
        required: true
        default: 'master'
      token:
        description: '1@checkout. token'
        required: true
        default: 'bc53e10960aa138d07e15d7eb95e6acf'
      owner:
        description: '1@checkout. owner'
        required: true
        default: 'openwz'
      project-name:
        description: '1@checkout. 项目名称'
        required: true
        default: 'react-web'
      ##################  nodejs ##########################  
      nvm-version:
        description: '2@nodejs. nvm 版本'
        required: true
        type: string
        default: '0.39.3'
      nodejs-version:
        description: '2@nodejs. nodejs 版本'
        required: true
        type: string
        default: '16.14.2'
      ##################  npm ##########################  
      project-path:
        description: '3@npm. 项目路径'
        required: true
        type: string
        default: './react-web'
      build-command:
        description: '3@npm. 构建命令'
        required: true
        type: string
        default: 'build'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1.自定义 [build-checkout] 插件
        id: checkout
        uses: wzjerrywz/github-actions/build-checkout@v1.16.1007
        with:
          branch-name: ${{ inputs.branch-name }}
          token: ${{ inputs.token }}
          owner: ${{ inputs.owner }}
          project-name: ${{ inputs.project-name }}

      - name: step2.自定义 [setup-nodejs] 插件
        id: nodejs
        uses: wzjerrywz/github-actions/setup-nodejs@v1.16.1007
        with:
          nvm-version: ${{ inputs.nvm-version }}
          nodejs-version: ${{ inputs.nodejs-version }}

      - name: step3.自定义 [build-npm] 插件
        id: npm
        uses: wzjerrywz/github-actions/build-npm@v1.16.1007
        with:
          project-path: ${{ inputs.project-path }}
          build-command: ${{ inputs.build-command }}
