name: setup--python

on:
  workflow_dispatch:
    inputs:
      conda-version:
        description: 'conda 版本'
        required: false
        type: string
        default: '0.39.3'
      python-version:
        description: 'python 版本'
        required: false
        type: string
        default: '3.12.6'
      virtual-env:
        description: '虚拟环境名称'
        required: false
        type: string
        default: 'virenv'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 使用自定义 [ setup-python ] 插件
        id: python
        uses: wzjerrywz/github-actions/setup-python@main
        with:
          conda-version: ${{ inputs.conda-version }}
          python-version: ${{ inputs.python-version }}
          virtual-env: ${{ inputs.virtual-env }}
