name: setup-gradle

on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: 'gradle 版本'
        required: true
        type: choice
        default: '9.1.0'
        options:
          - 9.1.0
          - 9.0.0
          - 8.14.2
          - 7.6.5
          - 7.6.4
      install-path:
        description: '安装路径'
        required: true
        default: './soft/gradle'           

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 自定义 [ setup-gradle ] 插件
        id: openjdk
        uses: wzjerrywz/github-actions/setup-gradle@v1.17.1011
        with:
          gradle-version: ${{ inputs.gradle-version }}
          install-path: ${{ inputs.install-path }}
