name: setup--nodejs

on:
  workflow_dispatch:
    inputs:
      nvm-version:
        description: 'nvm 版本'
        required: true
        type: string
        default: '0.39.3'
      nodejs-version:
        description: 'nodejs 版本'
        required: true
        type: string
        default: '16.14.2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 使用自定义 [ setup-nodejs ] 插件
        id: meact
        uses: wzjerrywz/github-actions/setup-nodejs@main
        with:
          nvm-version: ${{ inputs.nvm-version }}
          nodejs-version: ${{ inputs.nodejs-version }}
